# Generated by Django 5.0.7 on 2024-07-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfo.category'),
            preserve_default=False,
        ),
    ]
