# Generated by Django 5.0.7 on 2024-07-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0004_posts_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='posts',
        ),
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='portfo.category'),
            preserve_default=False,
        ),
    ]
