# Generated by Django 5.0.7 on 2024-07-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0005_remove_posts_posts_posts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
    ]
