# Generated by Django 5.0.7 on 2024-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0007_posts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
