# Generated by Django 5.0.7 on 2024-08-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0008_posts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artifact_images/')),
                ('article_link', models.URLField()),
            ],
        ),
    ]
