# Generated by Django 5.0.7 on 2024-08-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0009_artifactreflection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactreflection',
            name='article_link',
        ),
    ]
