# Generated by Django 5.0.7 on 2024-08-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0011_artifactreflection_additional_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactreflection',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
