# Generated by Django 5.0.7 on 2024-08-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0012_artifactreflection_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactreflection',
            name='intro',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifactreflection',
            name='second',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
