# Generated by Django 5.0.7 on 2024-08-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0014_artifactreflection_article_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactreflection',
            name='welcome',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
    ]
