# Generated by Django 5.0.7 on 2024-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0015_artifactreflection_welcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactreflection',
            name='welcome',
            field=models.TextField(),
        ),
    ]
