# Generated by Django 5.0.7 on 2024-08-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0016_alter_artifactreflection_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactreflection',
            name='infor',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
